#pragma once

#include <cstdint>
#include <string>

#include "utils.h"

namespace ltest::wmm {

struct FutureValue {
  int threadId;
  int location;
  // Note: we assume that all T types of the atomics fit
  // in uint64_t
  uint64_t encodedValue;
  // The maximum seq-number of the event which
  // must resolve the promise-event generated by
  // the write event which sent this future value
  //
  // In Demsky's paper it is write-event id + some small constant
  int maxPromiseResolveEventId;

  template <typename CastType>
  std::string AsString() const {
    return "FutureValue(tid=" + std::to_string(threadId) + ", value=" +
           std::to_string(decode_from_u64<CastType>(encodedValue)) +
           ", max_seqnum=" + std::to_string(maxPromiseResolveEventId) + ")";
  }
};

}  // namespace ltest::wmm